# coding=utf8

CONTINENTS_LOOKUP = {
                     "asia" : 1,
                     "north america" : 2,
                     "europe" : 3,
                     "africa" : 4,
                     "south america" : 5,
                     "oceania" : 6,
                     "australia" : 7,
                     "antarctica": 8
                    }

COUNTRIES_LOOKUP = {
                     "canada" : 9,
                     "the former yugoslav republic of macedonia" : 10,
                     "sao tome and principe" : 11,
                     "guinea-bissau" : 12,
                     "saint helena" : 13,
                     "lithuania" : 14,
                     "cambodia" : 15,
                     "ethiopia" : 16,
                     "aruba" : 17,
                     "swaziland" : 18,
                     "argentina" : 19,
                     "bolivia" : 20,
                     "cameroon" : 21,
                     "burkina faso" : 22,
                     "turkmenistan" : 23,
                     "ghana" : 24,
                     "saudi arabia" : 25,
                     "rwanda" : 26,
                     "japan" : 27,
                     "cape verde" : 28,
                     "united states minor outlying islands" : 29,
                     "pitcairn" : 30,
                     "guatemala" : 31,
                     "bosnia and herzegovina" : 32,
                     "kuwait" : 33,
                     "russian federation" : 34,
                     "jordan" : 35,
                     "dominica" : 36,
                     "liberia" : 37,
                     "maldives" : 38,
                     "jamaica" : 39,
                     "oman" : 40,
                     "tanzania" : 41,
                     "palestinian territory" : 42,
                     "albania" : 43,
                     "gabon" : 44,
                     "monaco" : 45,
                     "new zealand" : 46,
                     "yemen" : 47,
                     "jersey" : 48,
                     "andorra" : 49,
                     "greenland" : 50,
                     "samoa" : 51,
                     "norfolk island" : 52,
                     "united arab emirates" : 53,
                     "côte d'ivoire" : 54,
                     "india" : 55,
                     "azerbaijan" : 56,
                     "lesotho" : 57,
                     "saint vincent and the grenadines" : 58,
                     "kenya" : 59,
                     "south korea" : 60,
                     "tajikistan" : 61,
                     "turkey" : 62,
                     "afghanistan" : 63,
                     "bangladesh" : 64,
                     "mauritania" : 65,
                     "solomon islands" : 66,
                     "turks and caicos islands" : 67,
                     "saint lucia" : 68,
                     "san marino" : 69,
                     "mongolia" : 70,
                     "france" : 71,
                     "bermuda" : 72,
                     "slovakia" : 73,
                     "somalia" : 74,
                     "peru" : 75,
                     "laos" : 76,
                     "nauru" : 77,
                     "seychelles" : 78,
                     "norway" : 79,
                     "malawi" : 80,
                     "cook islands" : 81,
                     "benin" : 82,
                     "réunion" : 83,
                     "cuba" : 84,
                     "montenegro" : 85,
                     "saint kitts and nevis" : 86,
                     "togo" : 87,
                     "china" : 88,
                     "armenia" : 89,
                     "timor-leste" : 90,
                     "dominican republic" : 91,
                     "ukraine" : 92,
                     "bahrain" : 93,
                     "tonga" : 94,
                     "finland" : 95,
                     "south georgia" : 96,
                     "libya" : 97,
                     "cayman islands" : 98,
                     "central african republic" : 99,
                     "mauritius" : 100,
                     "liechtenstein" : 101,
                     "australia" : 102,
                     "british virgin islands" : 103,
                     "mali" : 104,
                     "sweden" : 105,
                     "bulgaria" : 106,
                     "united states" : 107,
                     "romania" : 108,
                     "angola" : 109,
                     "french southern territories" : 110,
                     "chad" : 111,
                     "south africa" : 112,
                     "tokelau" : 113,
                     "cyprus" : 114,
                     "brunei darussalam" : 115,
                     "qatar" : 116,
                     "malaysia" : 117,
                     "austria" : 118,
                     "vietnam" : 119,
                     "mozambique" : 120,
                     "uganda" : 121,
                     "hungary" : 122,
                     "niger" : 123,
                     "isle of man" : 124,
                     "brazil" : 125,
                     "falkland islands" : 126,
                     "faroe islands" : 127,
                     "guinea" : 128,
                     "panama" : 129,
                     "costa rica" : 130,
                     "luxembourg" : 131,
                     "bahamas" : 132,
                     "gibraltar" : 133,
                     "ireland" : 134,
                     "pakistan" : 135,
                     "palau" : 136,
                     "nigeria" : 137,
                     "ecuador" : 138,
                     "czech republic" : 139,
                     "belarus" : 140,
                     "iran" : 141,
                     "algeria" : 142,
                     "slovenia" : 143,
                     "el salvador" : 144,
                     "tuvalu" : 145,
                     "marshall islands" : 146,
                     "chile" : 147,
                     "belgium" : 148,
                     "kiribati" : 149,
                     "haiti" : 150,
                     "belize" : 151,
                     "sierra leone" : 152,
                     "georgia" : 153,
                     "mexico" : 154,
                     "gambia" : 155,
                     "philippines" : 156,
                     "moldova" : 157,
                     "morocco" : 158,
                     "croatia" : 159,
                     "micronesia" : 160,
                     "guernsey" : 161,
                     "thailand" : 162,
                     "switzerland" : 163,
                     "grenada" : 164,
                     "iraq" : 165,
                     "portugal" : 166,
                     "estonia" : 167,
                     "uruguay" : 168,
                     "equatorial guinea" : 169,
                     "lebanon" : 170,
                     "uzbekistan" : 171,
                     "tunisia" : 172,
                     "djibouti" : 173,
                     "heard island and mcdonald islands" : 174,
                     "antigua and barbuda" : 175,
                     "spain" : 176,
                     "colombia" : 177,
                     "burundi" : 178,
                     "fiji" : 179,
                     "barbados" : 180,
                     "cocos islands" : 181,
                     "madagascar" : 182,
                     "italy" : 183,
                     "curacao" : 184,
                     "bhutan" : 185,
                     "sudan" : 186,
                     "nepal" : 187,
                     "malta" : 188,
                     "democratic republic of the congo" : 189,
                     "netherlands" : 190,
                     "suriname" : 191,
                     "anguilla" : 192,
                     "venezuela" : 193,
                     "holy see" : 194,
                     "christmas island" : 195,
                     "indonesia" : 196,
                     "iceland" : 197,
                     "zambia" : 198,
                     "senegal" : 199,
                     "papua new guinea" : 200,
                     "trinidad and tobago" : 201,
                     "zimbabwe" : 202,
                     "germany" : 203,
                     "vanuatu" : 204,
                     "denmark" : 205,
                     "kazakhstan" : 206,
                     "poland" : 207,
                     "eritrea" : 208,
                     "kyrgyzstan" : 209,
                     "british indian ocean territory" : 210,
                     "montserrat" : 211,
                     "israel" : 212,
                     "north korea" : 213,
                     "sri lanka" : 214,
                     "latvia" : 215,
                     "south sudan" : 216,
                     "guyana" : 217,
                     "syria" : 218,
                     "sint maarten" : 219,
                     "honduras" : 220,
                     "myanmar" : 221,
                     "bouvet island" : 222,
                     "egypt" : 223,
                     "nicaragua" : 224,
                     "singapore" : 225,
                     "serbia" : 226,
                     "botswana" : 227,
                     "united kingdom" : 228,
                     "antarctica" : 229,
                     "congo" : 230,
                     "greece" : 231,
                     "paraguay" : 232,
                     "namibia" : 233,
                     "comoros" : 234,
                    }

STATES_LOOKUP = {
                  "delaware" : 235,
                  "north dakota" : 236,
                  "washington" : 237,
                  "rhode island" : 238,
                  "tennessee" : 239,
                  "iowa" : 240,
                  "nevada" : 241,
                  "maine" : 242,
                  "colorado" : 243,
                  "mississippi" : 244,
                  "south dakota" : 245,
                  "new jersey" : 246,
                  "oklahoma" : 247,
                  "wyoming" : 248,
                  "minnesota" : 249,
                  "north carolina" : 250,
                  "illinois" : 251,
                  "new york" : 252,
                  "arkansas" : 253,
                  "indiana" : 254,
                  "maryland" : 255,
                  "louisiana" : 256,
                  "idaho" : 257,
                  "district of columbia" : 258,
                  "arizona" : 259,
                  "wisconsin" : 260,
                  "michigan" : 261,
                  "kansas" : 262,
                  "utah" : 263,
                  "virginia" : 264,
                  "oregon" : 265,
                  "connecticut" : 266,
                  "montana" : 267,
                  "california" : 268,
                  "massachusetts" : 269,
                  "vermont" : 270,
                  "georgia" : 271,
                  "pennsylvania" : 272,
                  "florida" : 273,
                  "alaska" : 274,
                  "kentucky" : 275,
                  "missouri" : 276,
                  "nebraska" : 277,
                  "new hampshire" : 278,
                  "texas" : 279,
                  "west virginia" : 280,
                  "south carolina" : 281,
                  "ohio" : 282,
                  "alabama" : 283,
                  "new mexico" : 284,
                }

OCEANS_LOOKUP = {
                  "south pacific ocean" : 285,
                  "amazon river" : 286,
                  "barents sea" : 287,
                  "bay of fundy" : 288,
                  "sea of okhotsk" : 289,
                  "viscount melville sound" : 290,
                  "great australian bight" : 291,
                  "drake passage" : 292,
                  "bering sea" : 293,
                  "luzon strait" : 294,
                  "andaman sea" : 295,
                  "taiwan strait" : 296,
                  "gulf of aden" : 297,
                  "gulf of mannar" : 298,
                  "gulf of guinea" : 299,
                  "golfo de panamá" : 300,
                  "persian gulf" : 301,
                  "gulf of maine" : 302,
                  "bay of biscay" : 303,
                  "ross  sea" : 304,
                  "java sea" : 305,
                  "hudson bay" : 306,
                  "chesapeake bay" : 307,
                  "río de la plata" : 308,
                  "laccadive sea" : 309,
                  "gulf of carpentaria" : 310,
                  "gulf of alaska" : 311,
                  "east china sea" : 312,
                  "baltic sea" : 313,
                  "red sea" : 314,
                  "weddell  sea" : 315,
                  "shelikhova gulf" : 316,
                  "celebes sea" : 317,
                  "balearic sea" : 318,
                  "james bay" : 319,
                  "melville bay" : 320,
                  "straits of florida" : 321,
                  "amundsen gulf" : 322,
                  "bellingshausen sea" : 323,
                  "mediterranean sea" : 324,
                  "white  sea" : 325,
                  "gulf of tonkin" : 326,
                  "arabian sea" : 327,
                  "south atlantic ocean" : 328,
                  "davis  strait" : 329,
                  "beaufort  sea" : 330,
                  "north pacific ocean" : 331,
                  "sea of japan" : 332,
                  "ionian sea" : 333,
                  "english channel" : 334,
                  "inner sea" : 335,
                  "arctic ocean" : 336,
                  "strait of singapore" : 337,
                  "gulf of kutch" : 338,
                  "gulf of bothnia" : 339,
                  "ungava bay" : 340,
                  "adriatic sea" : 341,
                  "arafura sea" : 342,
                  "gulf of oman" : 343,
                  "bo hai" : 344,
                  "hudson strait" : 345,
                  "bay of plenty" : 346,
                  "makassar strait" : 347,
                  "bristol channel" : 348,
                  "ceram sea" : 349,
                  "cook inlet" : 350,
                  "yellow sea" : 351,
                  "kara sea" : 352,
                  "molucca sea" : 353,
                  "bering strait" : 354,
                  "great barrier reef" : 355,
                  "caribbean  sea" : 356,
                  "southern ocean" : 357,
                  "columbia river" : 358,
                  "tasman  sea" : 359,
                  "labrador sea" : 360,
                  "korea strait" : 361,
                  "sulu sea" : 362,
                  "golfe du lion" : 363,
                  "bristol bay" : 364,
                  "coral sea" : 365,
                  "golfo san jorge" : 366,
                  "north atlantic ocean" : 367,
                  "irish sea" : 368,
                  "bismarck sea" : 369,
                  "norwegian sea" : 370,
                  "mozambique channel" : 371,
                  "gulf of finland" : 372,
                  "timor sea" : 373,
                  "baha de campeche" : 374,
                  "golfo de california" : 375,
                  "gulf of honduras" : 376,
                  "yangtze river" : 377,
                  "laptev sea" : 378,
                  "greenland sea" : 379,
                  "chukchi sea" : 380,
                  "bay of bengal" : 381,
                  "indian ocean" : 382,
                  "baffin bay" : 383,
                  "scotia sea" : 384,
                  "strait of malacca" : 385,
                  "gulf of mexico" : 386,
                  "black sea" : 387,
                  "the north western passages" : 388,
                  "gulf of thailand" : 389,
                  "solomon sea" : 390,
                  "gulf of st. lawrence" : 391,
                  "tyrrhenian sea" : 392,
                  "strait of gibraltar" : 393,
                  "aegean sea" : 394,
                  "caspian sea" : 395,
                  "amundsen sea" : 396,
                  "north sea" : 397,
                  "south china sea" : 398,
                  "philippine sea" : 399,
                  "inner seas" : 400,
                  "sargasso sea" : 401,
                  "banda sea" : 402
                 }